name: Release

on:
    repository_dispatch:
        types: [release_trigger]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Token
        id: get_workflow_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.ICUB_TECH_CODE_KEY }}
          app_id: ${{ secrets.ICUB_TECH_CODE_ID }}
          repository: icub-tech-iit/code
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: Code ${{ github.event.client_payload.version }}
          body: |
            Release ${{ github.event.client_payload.version }}
          draft: false
          prerelease: false

      - name: Repository Dispatch for appsAway
        uses: peter-evans/repository-dispatch@v1
        env:
          GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          token: ${{ env.GITHUB_APPS_TOKEN }}
          repository: icub-tech-iit/appsAway
          event-type: code_trigger
          client-payload: '{"version": "${{ github.event.client_payload.version }}"}'

      - name: Repository Dispatch for building images
        uses: peter-evans/repository-dispatch@v1
        env:
          GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          token: ${{ env.GITHUB_APPS_TOKEN }}
          repository: icub-tech-iit/code
          event-type: repository_trigger
          client-payload: '{"version": "${{ steps.get_version.outputs.VERSION }}", "type": "repository_trigger", "img_list": "superbuild superbuild-tensorflow-cpu superbuild-tensorflow-gpu superbuild-pytorch superbuild-icubhead superbuild-nvidia superbuild-nvidia-10.1 superbuild-gazebo blender gazebo"}'
