name: Release

on:
    repository_dispatch:
        types: [release_trigger]
    
    workflow_dispatch:
      inputs:
        version:
          description: 'version of superbuild'
          required: true
          default: '2022.x.y'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Version
        id: get_version
        run: | 
             if [[ "${{github.event_name}}" == "repository_dispatch" ]]
             then
              echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT 
             else
              echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT 
             fi
      - name: Debug
        id: debug
        run : echo "my version is ${{ steps.get_version.outputs.version }}"
      - name: Check Tag
        id: check_tag
        uses: mukunku/tag-exists-action@v1.2.0
        with: 
          tag: 'steps.get_version.outputs.version'
      - run: echo "Does the tag exist?  ${{ steps.checkTag.outputs.exists }} "
      - name: Create Release
        id: create_release
        if: ${{ steps.checkTag.outputs.exists }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ steps.get_version.outputs.version }}
          release_name: Deployment  ${{ steps.get_version.outputs.version }}
          body: |
            Release  ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      # - name: Repository Dispatch for appsAway
      #   uses: peter-evans/repository-dispatch@v1
      #   env:
      #     GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      #   with:
      #     token: ${{ env.GITHUB_APPS_TOKEN }}
      #     repository: icub-tech-iit/appsAway
      #     event-type: code_trigger
      #     client-payload: '{"version": "${{ github.event.client_payload.version }}"}'

      - name: Repository Dispatch for building images
        uses: peter-evans/repository-dispatch@v1
        env:
          GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: valegagge/Deployment
          event-type: repository_trigger
          client-payload: '{"version": "${{ steps.get_version.outputs.version }}", "type": "repository_trigger", "img_list": "superbuild superbuild-tensorflow-cpu superbuild-tensorflow-gpu superbuild-pytorch superbuild-icubhead superbuild-nvidia superbuild-nvidia-10.1 superbuild-gazebo blender gazebo"}'
